service: alarm-setting-checker

custom: ${file(./conf/custom.yml)}

provider:
  name: aws
  runtime: python3.11
  region: ${param:region, "ap-northeast-1"}
  stage: "dev"
  role: ${param:role_str, "${self:custom.execRole.${self:provider.tags.accountName}}"}
  deploymentBucket:
    name: ${param:depbucket, "${self:custom.bucket.${self:provider.tags.accountName}}"}
  stackTags:
    CheckAlarmSetting: ${opt:check_alarm, 'NO'}
  tags:
    accountName: ${param:account_name, "core"}
  # 各関数の共通設定
  memorySize: 128
  timeout: 300
  # 環境変数
  environment: ${file(./conf/env.yml)}

functions:
  main:
    handler: lambda_function.lambda_handler
    description: "監視アラーム設定をチェック"
    # 各関数の共通設定
    memorySize: 128
    timeout: 300
    # 環境変数
    environment: ${file(./conf/env.yml)}
    # スケジュールイベント
    events: ${file(./conf/event.yml)}

# CloudFormation テンプレート記述用ブロック
## dev/prod でファイルを分けている
resources: ${file(./conf/resources-${sls:stage}.yml)}