AWSTemplateFormatVersion: 2010-09-09
Description: Fargate Create
# From https://dev.classmethod.jp/articles/cloudformation-fargate/
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Project Name Prefix"
        Parameters:
          - ProjectName
      - Label:
          default: "Fargate for ECS Configuration"
        Parameters:
          - ECSClusterName
          - ECSTaskName
          - ECSTaskCPUUnit
          - ECSTaskMemory
          - ECSImageName
          - ECSTaskDesiredCount

    ParameterLabels:
      ECSClusterName:
        default: "ECSClusterName"
      ECSTaskName:
        default: "ECSTaskName"
      ECSTaskCPUUnit:
        default: "ECSTaskCPUUnit"
      ECSTaskMemory:
        default: "ECSTaskMemory"
      ECSImageName:
        default: "ECSImageName"
      ECSTaskDesiredCount:
        default: "ECSTaskDesiredCount"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  ProjectName:
    Default: kaji-test
    Type: String

  # ECSClusterName
  ECSClusterName:
    Type: String
    Default: "cluster"

  # ECSTaskName
  ECSTaskName:
    Type: String
    Default: "task"

  # ECSTaskCPUUnit
  ECSTaskCPUUnit:
    AllowedValues: [256, 512, 1024, 2048, 4096]
    Type: String
    Default: "256"

  # ECSTaskMemory
  ECSTaskMemory:
    AllowedValues: [256, 512, 1024, 2048, 4096]
    Type: String
    Default: "512"

  # ECSContainerName for apache container
  ECSContainerName1:
    Type: String
    Default: "container"

  # ECSImageName for apache container
  ECSImageName1:
    Type: String
    Default: "xxxxxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/kaji-test-ecr:latest"

  # ECSTaskDesiredCount
  ECSTaskDesiredCount:
    Type: Number
    Default: 1

  ECSTaskExecutionRole:
    Type: String
    Default: arn:aws:iam::88888888888:role/ecsTaskExecutionRole

  LogGroup:
    Type: String
    Default: "/ecs/"

  TaskMinContainerCount:
    Type: Number
    Description: Minimum number of containers to run for the service
    Default: 1
    MinValue: 1
    ConstraintDescription: Value must be at least one

  TaskMaxContainerCount:
    Type: Number
    Description: Maximum number of containers to run for the service when auto scaling out
    Default: 2
    MinValue: 1
    ConstraintDescription: Value must be at least one

Resources:
  # ------------------------------------------------------------#
  # ECS Cluster
  # ------------------------------------------------------------#
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      CapacityProviders:
        - "FARGATE_SPOT"
      ClusterName: !Sub "${ProjectName}-${ECSClusterName}"
      DefaultCapacityProviderStrategy:
        - CapacityProvider: "FARGATE_SPOT"

  # ------------------------------------------------------------#
  #  ECS LogGroup
  # ------------------------------------------------------------#
  ECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "${LogGroup}/${ProjectName}"

  # ------------------------------------------------------------#
  #  ECS TaskDefinition
  # ------------------------------------------------------------#
  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Cpu: !Ref ECSTaskCPUUnit
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Family: !Sub "${ProjectName}-task"
      Memory: !Ref ECSTaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

      # ContainerDefinitions
      ContainerDefinitions:
        # [Apache Container]
        - Name: !Sub "${ProjectName}"
          Image: !Ref ECSImageName1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-datetime-format: "%Y-%m-%d %H:%M:%S"
              awslogs-stream-prefix: !Sub "${ProjectName}"
          Secrets:
            - Name: AWS_ACCESS_KEY_ID
              ValueFrom: arn:aws:ssm:ap-northeast-1:88888888888:parameter/wordpress-server-construction-with-kusanagi/ACCESSKEYID
            - Name: AWS_SECRET_ACCESS_KEY
              ValueFrom: arn:aws:ssm:ap-northeast-1:88888888888:parameter/wordpress-server-construction-with-kusanagi/SECRETACCESKEY
            - Name: CHATWORK_TOKEN
              ValueFrom: arn:aws:ssm:ap-northeast-1:88888888888:parameter/wordpress-server-construction-with-kusanagi/CHATWORKTOKEN
